### PR TITLE
Sign Drone to fix acceptance test

### PR DESCRIPTION
**Pull request by sulthan-ahmed**

### CODE REVIEW

**Comment by lennym** [comment]
The tests are passing on master. I don't think this is needed.

**Comment by sulthan-ahmed** [comment]
yeah I think you already put in a signature after I submitted this PR

**Comment by lennym** [comment]
I got there 3 hours before. #justsayin 😉

**Comment by sulthan-ahmed** [comment]
Lol, Really? I did this yesterday, I had my builds fail because of the whole signing thing that's why I put in the PR. 
Alt Text

**Pull request closed without merging**
