### PR TITLE
Add missing tenancy-start acceptance tests

### PR DESCRIPTION
**Pull request by sulthan-ahmed**

### CODE REVIEW

**Comment by lennym** [comment]
The code seems ok to me, but obviously pending a build from #20

**Comment by lennym** [comment]
Also needs moar rebase.

**Comment by JoeChapman** [comment]
I concur with @lennym

**Comment by sulthan-ahmed** [comment]
It's now been rebased and builds have passed, are you ok to approve it @JoeChapman ?

**Pull request merged**
